### PR TITLE
BugFix: Fixed an issue where JDBC OceanBaseSink might cause data loss in non-primary key tables

### LINKED ISSUE #109: [Bug]: JDBC OceanBaseSink may cause data loss for non-primary key tables.
### Describe the bug

JDBC OceanBaseSink may cause data loss for non-primary key tables.

DataChangeRecord.KeyExtractor.simple() does not correctly handle the case where the primary key list is empty, it just handles it as null. Non-primary key tables will be mistakenly treated as primary key tables.

### Environment

flink-connector-oceanbase-1.4

### Fast reproduce steps

Call `OceanBaseSink` directly.

### Expected behavior

_No response_

### Actual behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yuanoOo**
## Summary

fix #109

### CODE REVIEW

File: flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/DataChangeRecord.java [hunk 1]
```diff
@@ -36,11 +37,15 @@ static KeyExtractor simple() {
...
                             .map(
-                                    keys ->
-                                            new DataChangeRecordData(
-                                                    keys.stream()
-                                                            .map(record::getFieldValue)
-                                                            .toArray()))
+                                    keys -> {
+                                        Object[] array =
+                                                keys.stream().map(record::getFieldValue).toArray();
+                                        if (array.length == 0) {
```
Comment (whhe) [inline flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/DataChangeRecord.java:43]: What's it for? The process should directly go to `orElse` if the record is from a non-pk table,

Comment (yuanoOo) [reply flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/DataChangeRecord.java:43]: https://github.com/oceanbase/flink-connector-oceanbase/blob/f7f175f62991c63fb63a1e30c9a4ca0af60420ee/flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseWriter.java#L132-L144

- If record.getTable().getKey() is an empty but not null primary key List, this `KeyExtractor.simple()` will return an empty DataChangeRecord object but not NULL
- Then line 133 of the code block above will return false, causing the non-primary key table to be mistakenly treated as the primary key table.

```
        static KeyExtractor simple() {
            return record ->
                    // when record.getTable().getKey() is empty List
                    Optional.ofNullable(record.getTable().getKey())
                            .map(
                                    keys ->
                                            new DataChangeRecordData(
                                                    keys.stream()
                                                            .map(record::getFieldValue)
                                                            .toArray()))
                            .orElse(null);
        }
```

**Review by whhe — APPROVED** [review]
